/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package window;

/**
 *
 * @author student
 */
public class Win28_圖片1 extends javax.swing.JFrame {

    /**
     * Creates new form Win28圖片2
     */
    public Win28_圖片1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl圖片 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdo企鵝 = new javax.swing.JRadioButton();
        rdo小貓 = new javax.swing.JRadioButton();
        rdo小狗 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl圖片.setBackground(new java.awt.Color(255, 255, 204));
        lbl圖片.setOpaque(true);
        getContentPane().add(lbl圖片);
        lbl圖片.setBounds(150, 20, 130, 150);

        jPanel1.setLayout(null);

        buttonGroup1.add(rdo企鵝);
        rdo企鵝.setText("企鵝");
        rdo企鵝.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                選項鈕選圖片(evt);
            }
        });
        jPanel1.add(rdo企鵝);
        rdo企鵝.setBounds(30, 20, 47, 21);

        buttonGroup1.add(rdo小貓);
        rdo小貓.setText("小貓");
        rdo小貓.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                選項鈕選圖片(evt);
            }
        });
        jPanel1.add(rdo小貓);
        rdo小貓.setBounds(30, 70, 47, 21);

        buttonGroup1.add(rdo小狗);
        rdo小狗.setText("小狗");
        rdo小狗.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                選項鈕選圖片(evt);
            }
        });
        jPanel1.add(rdo小狗);
        rdo小狗.setBounds(30, 100, 47, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 190, 180, 170);

        setSize(new java.awt.Dimension(491, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void 選項鈕選圖片(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_選項鈕選圖片
        if (rdo企鵝.isSelected()) {
            lbl圖片.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ani1.jpg"))); // NOI18N
        } else if (rdo小貓.isSelected()) {
            lbl圖片.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ani2.jpg"))); // NOI18N
        } else {
            lbl圖片.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ani3.jpg"))); // NOI18N
        }
    }//GEN-LAST:event_選項鈕選圖片

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Win28_圖片1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Win28_圖片1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Win28_圖片1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Win28_圖片1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Win28_圖片1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl圖片;
    private javax.swing.JRadioButton rdo企鵝;
    private javax.swing.JRadioButton rdo小狗;
    private javax.swing.JRadioButton rdo小貓;
    // End of variables declaration//GEN-END:variables
}
