/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package window;

import javax.swing.JButton;

/**
 *
 * @author student
 */
public class Win30_打字 extends javax.swing.JFrame {

    /**
     * Creates new form Win30_打字
     */
    public Win30_打字() {
        initComponents();
        txtInput.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btndelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtInput);
        txtInput.setBounds(72, 31, 195, 53);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(80, 140, 40, 30);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(140, 140, 40, 30);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                數字(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(200, 140, 40, 30);

        btndelect.setText("刪除<-");
        btndelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                刪除(evt);
            }
        });
        getContentPane().add(btndelect);
        btndelect.setBounds(80, 210, 72, 23);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void 數字(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_數字
        JButton btn = (JButton) evt.getSource();

        if (txtInput.getText().equals("0")) {
            txtInput.setText("");
        }

        txtInput.setText(txtInput.getText() + btn.getText());
    }//GEN-LAST:event_數字

    private void 刪除(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_刪除
        int len;
        len = txtInput.getText().length();

        if (len != 0) {
            String str = txtInput.getText().substring(0, len - 1);
            txtInput.setText(str);
            if (txtInput.getText().length() == 0) {
                txtInput.setText("0");
            }
        }
    }//GEN-LAST:event_刪除

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Win30_打字.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Win30_打字.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Win30_打字.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Win30_打字.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Win30_打字().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btndelect;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
